2020-12-22 12:34:50,443 ERROR: Exception on /index [GET] [in /home/radek/PycharmProjects/microblog/flask_venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/radek/PycharmProjects/microblog/flask_venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/radek/PycharmProjects/microblog/flask_venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/radek/PycharmProjects/microblog/flask_venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/radek/PycharmProjects/microblog/flask_venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/radek/PycharmProjects/microblog/flask_venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/radek/PycharmProjects/microblog/flask_venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/radek/PycharmProjects/microblog/flask_venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/radek/PycharmProjects/microblog/app/routes.py", line 43, in index
    return render_template('index.html', title='Home', form=form, posts=posts.items, prev_url=prev_url)
  File "/home/radek/PycharmProjects/microblog/flask_venv/lib/python3.8/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/radek/PycharmProjects/microblog/flask_venv/lib/python3.8/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/radek/PycharmProjects/microblog/flask_venv/lib/python3.8/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/radek/PycharmProjects/microblog/flask_venv/lib/python3.8/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/radek/PycharmProjects/microblog/flask_venv/lib/python3.8/site-packages/jinja2/loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "/home/radek/PycharmProjects/microblog/flask_venv/lib/python3.8/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/home/radek/PycharmProjects/microblog/flask_venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/radek/PycharmProjects/microblog/flask_venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/radek/PycharmProjects/microblog/app/templates/index.html", line 24, in template
    <a href="{% next_url or '#' %}">
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'next_url'. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2020-12-22 12:36:00,019 ERROR: Exception on /explore [GET] [in /home/radek/PycharmProjects/microblog/flask_venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/radek/PycharmProjects/microblog/flask_venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/radek/PycharmProjects/microblog/flask_venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/radek/PycharmProjects/microblog/flask_venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/radek/PycharmProjects/microblog/flask_venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/radek/PycharmProjects/microblog/flask_venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/radek/PycharmProjects/microblog/flask_venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/radek/PycharmProjects/microblog/flask_venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/radek/PycharmProjects/microblog/app/routes.py", line 190, in explore
    return render_template('index.html', title='Explore', posts=posts.items, next_url=next_url, prev_url=prev_url)
  File "/home/radek/PycharmProjects/microblog/flask_venv/lib/python3.8/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/radek/PycharmProjects/microblog/flask_venv/lib/python3.8/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/radek/PycharmProjects/microblog/flask_venv/lib/python3.8/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/radek/PycharmProjects/microblog/flask_venv/lib/python3.8/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/radek/PycharmProjects/microblog/flask_venv/lib/python3.8/site-packages/jinja2/loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "/home/radek/PycharmProjects/microblog/flask_venv/lib/python3.8/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/home/radek/PycharmProjects/microblog/flask_venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/radek/PycharmProjects/microblog/flask_venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/radek/PycharmProjects/microblog/app/templates/index.html", line 24, in template
    <a href="{% next_url or '#' %}">
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'next_url'. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2020-12-22 12:36:01,068 ERROR: Exception on /index [GET] [in /home/radek/PycharmProjects/microblog/flask_venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/radek/PycharmProjects/microblog/flask_venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/radek/PycharmProjects/microblog/flask_venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/radek/PycharmProjects/microblog/flask_venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/radek/PycharmProjects/microblog/flask_venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/radek/PycharmProjects/microblog/flask_venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/radek/PycharmProjects/microblog/flask_venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/radek/PycharmProjects/microblog/flask_venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/radek/PycharmProjects/microblog/app/routes.py", line 43, in index
    return render_template('index.html', title='Home', form=form, posts=posts.items, prev_url=prev_url)
  File "/home/radek/PycharmProjects/microblog/flask_venv/lib/python3.8/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/radek/PycharmProjects/microblog/flask_venv/lib/python3.8/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/radek/PycharmProjects/microblog/flask_venv/lib/python3.8/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/radek/PycharmProjects/microblog/flask_venv/lib/python3.8/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/radek/PycharmProjects/microblog/flask_venv/lib/python3.8/site-packages/jinja2/loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "/home/radek/PycharmProjects/microblog/flask_venv/lib/python3.8/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/home/radek/PycharmProjects/microblog/flask_venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/radek/PycharmProjects/microblog/flask_venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/radek/PycharmProjects/microblog/app/templates/index.html", line 24, in template
    <a href="{% next_url or '#' %}">
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'next_url'. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
